### ISSUE TITLE
Update NextJS to v12

### ISSUE THREAD

**Issue by hwong0305** [garageScript/c0d3-app#1264]

**Comment by songz** [comment]
Update, [this link](https://github.com/garageScript/c0d3-app/blob/master/helpers/apolloClient.ts#L38) gives an issue because v12 supports only `import` and it seems like dynamic requires are broken.

When we move the `require` to the top of the file and change it to import, it causes an error because client side apolloClient cannot run graphql `schema` files. Therefore, some refactoring would need to be done so the pages that use server side static generation (like [curriculum page](https://github.com/garageScript/c0d3-app/blob/master/pages/curriculum.tsx#L220) )uses a separate file that imports the server side `schema` files.
