### ISSUE TITLE
Description accordion gets cut of view when its body height is long

### ISSUE THREAD

**Issue by flacial** [garageScript/c0d3-app#1517]
**Issue:** Description accordion gets cut when the submission file is shorter than the description body.

<img width="1302" alt="image" src="https://user-images.githubusercontent.com/35906419/155324534-649477f5-ed1d-435c-8664-a841612eadcd.png">

**Potential solution:** Remove its `absolute` style property

**Comment by SlyBouhafs** [comment]
@flacial I will work on this one. There are two alternative solutions, either the accordion won't be superimposed on the submission by removing the `absolute` property, or we can remove the `overflow` hidden class from the parent element so that it can overflow without having the rest of it hidden, like this:

![Screen Shot 2022-03-10 at 13 52 40](https://user-images.githubusercontent.com/1410462/157665663-7b3371c4-f142-430a-b7e5-80b0dbc3b2e7.png)

**Comment by flacial** [comment]
> we can remove the overflow hidden class from the parent element so that it can overflow without having the rest of it hidden, like this.

I think this is the most visually appealing, but wouldn't it cover the next user challenge submission if the current submission diffView is tiny? Like in the following image:

![image](https://user-images.githubusercontent.com/35906419/157667909-c725ef1e-5d12-46dd-b5c8-8087c91305bb.png)

**Comment by SlyBouhafs** [comment]
> I think this is the most visually appealing, but wouldn't it cover the next user challenge submission if the current submission diffView is tiny?

Yes it will cover the rest of submissions if the description is long, but i don't think it will be an issue, the challenge description accordion is collapsible, so once the mentor is done with the description, the description can be hidden again.

**Comment by flacial** [comment]
Sounds good. It seems it needs an "auto collapse when another submission diffView or body is clicked" feature. But that's something different.
