### ISSUE TITLE
I keep on seeing the Connect to Discord popup

### ISSUE THREAD

**Issue by anthonykhoa** [garageScript/c0d3-app#1527]
When i go to c0d3.com I sometimes see that Connect to Discord popup that has options to either `No thanks, I'll study on my own.` or `Connect now`.. even though I clicked one of these options awhile back already.
I am able to reproduce this in production by clearing localstorage `localStorage.clear()`
In our curriculum we even have a section on localStorage. This means that there is a high potential for students to come across this issue because they might try out localstorage functions in t heir browsers.

Additionally, i expect(`I havent tried yet`) that if a person tries to user another browser, they'll come across the issue as well. 

I don't know exact specifics of implementation, but if we are relying on localStorage in order to store persisting data, then that is a bad idea. Its bad because localStorage is dependent on the user. For saving persisting data we should utilize the backend.

**Comment by flacial** [comment]
In the following scenario:

→ Login with c0d3
→ Connect to discord
→ Discord redirects back to c0d3.com

The modal "Connect to discord" appears, and the user discord image doesn't appear in the AppNav. It's because the GraphQL queries have the fetch policy as `cache-first` by default, which will always get the data from the cache. 

There's another policy called `cache-and-network` that first gets the data from the cache, fetches the newest data from the server, and updates the cache; As appealing as it might sound, it doesn't work well.

The one that fixes it is called `network-only` which won't get the data first from the cache but only updates it with the new data. Combined with `nextFetchPolicy: 'cache-and-network'`, we can make sure the first query isn't from the cache and any other queries from the cache.
