### ISSUE TITLE
Admin - lessons form input not working

### ISSUE THREAD

**Issue by songz** [garageScript/c0d3-app#1549]
Steps to reproduce: 

1. https://www.c0d3.com/admin/lessons
2. Click into the text area. When you try to edit the middle of the word, the cursor keeps jumping to the end

**Comment by SlyBouhafs** [comment]
@songz I was able to find the piece of code that is causing the issue, but i am not sure why it is there.
https://github.com/garageScript/c0d3-app/blob/master/components/MdInput.tsx#L56

```js
    if (internalState.value !== value) {
      // Value was updated externally, reset component history
      reset({
        value,
        selectionStart: value.length,
        selectionEnd: value.length
      })
      return
    }
```

When i remove it, the issue doesn't happen anymore, since i am not exactly what the comment mean, i am not sure if removing it is a good solution. What is meant by updated externally in the comment?

**Comment by songz** [comment]
The review component uses this component and it seems to be working well, could we take a look at how:

1. review is using this component?
2. How admin is using this component?

compare the difference?

**Comment by flacial** [comment]
The issue is harder to identify than I thought. But in a [nutshell](https://stackoverflow.com/a/48608293).
