### ISSUE TITLE
Add a `yarn test` script for Windows

### ISSUE THREAD

**Issue by flacial** [garageScript/c0d3-app#1976]
Some of our engineers use Windows, and setting environment variables in PowerShell or CMD is different from Linux.
`TZ=UTC` has to become `set TZ=UTC` on Windows.

To resolve this issue, add scripts with the following format `action:windows` for each script that sets an env variable.

Example:

- `test:windows: "set TZ=UTC && yarn test --coverage --runInBand"`

**Comment by JasirZaeem** [comment]
It would be better to use something like cross-env https://www.npmjs.com/package//cross-env for cases like this instead of creating separate platform specifics commands. 

Regarding this particular problem, using `set TZ=UTC` has not fixed the problem for me when I have tried it in the past, while the environment variable does get set, it does not have the same effect on windows as it does on linux so a different way to fix it will be needed.

**Comment by JasirZaeem** [comment]
@HS-90 You are right! setting TZ works on windows with node versions greater thaan 16.20 and since vercel has added support for node 16 now we can use node 16 in our dev environments, earlier we were on node 14. So yeah you can fix it by setting TZ now. I'd recommend looking into cross-env still instead of creating a separate script for windows.
