### ISSUE TITLE
Ignore removed files from showing in the submission files

### ISSUE THREAD

**Issue by flacial** [garageScript/c0d3-app#3066]
### Expected behavior

Deleted files should not be showing as `/dev/null`

<img width="1342" alt="image" src="https://github.com/garageScript/c0d3-app/assets/35906419/8c1d0b2f-49b9-491c-b26f-c83c78191d3e">

### Actual behavior

They're showing as `/dev/null`

<img width="1349" alt="image" src="https://github.com/garageScript/c0d3-app/assets/35906419/69e8495d-324c-4056-a417-c7582ef2d68c">

**Comment by kondanna** [comment]
Brainstorming potential approaches. I could be way off because after two years this codebase is pretty foreign to me, so take this as a "thinking out loud" comment.

1. Stop CLI from submitting the non-files to c0d3-app:
https://github.com/garageScript/c0d3-cli/blob/master/src/util/git.ts
https://github.com/garageScript/c0d3-cli/blob/master/src/commands/submit.ts

Seems like the most elegant solution as it's the most "upstream." Unless it's not possible,  in which case

2. Do something with the submitted diff at the resolver level:
https://github.com/garageScript/c0d3-app/blob/f58afafcdf98faae84df686a0a69463097f515ee/graphql/resolvers/submissionController.ts

3. Just don't render it at the component level:
https://github.com/garageScript/c0d3-app/blob/f58afafcdf98faae84df686a0a69463097f515ee/components/DiffView/DiffView.tsx

**Comment by kondanna** [comment]
After further review, it looks like the CLI just pushes a 'diff' into the resolver, and the diff is only processed into files at DiffView. So #3 looks to be the approach to take.

**Comment by SlyBouhafs** [comment]
Do you think we should just hide them on the component side or avoid sending them from the c0d3-cli?

**Comment by flacial** [comment]
> @flacial Do you think we should just hide them on the component side or avoid sending them from the c0d3-cli?

@SlyBouhafs "Avoid sending them from c0d3-cli" is the way. It shouldn't send them by default; if it does, there appears to be an issue with our logic. With that said, we could begin with a swift solution, such as hiding them at the component level, to address the problem. Subsequently, we can investigate the underlying causes.
